import mongoose from "mongoose";

const Deck = new mongoose.Schema({
    deckName: {
        type: String,
        required: [true, 'Must provide deck name']
    },

    deckLang: {
        type: String,
        required: [true, 'Must provide deck language']
    },

    creator: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: [true, "Must provide the creator of the deck"]
    },
    
    words: [
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Word'
        }
    ],
    autoGenerated: {
        type: Boolean,
        default: false
    },
    parent: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Deck',
        default: null
    }
});

export default mongoose.model('Deck', Deck);
